# LUEGO CREAR UN ARCHIVO docker-compose.yml colocando la imagen de mongo que se descargo  y tambien el puerto que se harà la conexion que es el puerto 3000

version: '3'

services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=2500
      - MONGODB_CNN=mongodb://mongo:27017/test
    ports:
      - "2500:2500"
  mongo:
    image: mongo